# Metis Introduction to Data Science Course Project
## Felipe Rios Ribeiro

### What is the question you hope to answer?

I selected a challenge from Kaggle named "House Prices - Advanced Regression Techniques", available at https://www.kaggle.com/c/house-prices-advanced-regression-techniques/overview.

#### How might we predict house prices using key data and features from houses such as area, age, location, style, condition, etc.

### What data are you planning to use to answer that question?

The available data for this challenge can be found here: https://www.kaggle.com/c/house-prices-advanced-regression-techniques/data

1. Train.csv 

2. Test.csv

### Steps

* Import data and libraries
* Understand Train and Test datasets
* Cleaning
* Understand Sale Price (target variable)
* Remove missing values from Train
* Determine the most important variables for Sale Price (correlation)
* Run a multi-linear regression with the most important variables

### <span style='background :yellow' > Import data and libraries

In [98]:
#libraries for data handling/modeling
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn import metrics
import scipy.stats as stats
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

#libraries for visualization
%matplotlib inline
import seaborn as sns
import matplotlib.pyplot as plt

#Train data 
fullData = pd.read_csv("/Users/feliperiosribeiro/METIS_project_Felipe/data/train.csv")

#Test data 
#Test = pd.read_csv("/Users/feliperiosribeiro/METIS_project_Felipe/data/test.csv")

### <span style='background :yellow' > Understand Train and Test datasets

#### Train data

In [99]:
# Train data
fullData.tail()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
1455,1456,60,RL,62.0,7917,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,175000
1456,1457,20,RL,85.0,13175,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,2,2010,WD,Normal,210000
1457,1458,70,RL,66.0,9042,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,GdPrv,Shed,2500,5,2010,WD,Normal,266500
1458,1459,20,RL,68.0,9717,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,142125
1459,1460,20,RL,75.0,9937,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2008,WD,Normal,147500

In [100]:
Train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 81 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1460 non-null   int64
 1   MSSubClass     1460 non-null   int64
 2   MSZoning       1460 non-null   object
 3   LotFrontage    1201 non-null   float64
 4   LotArea        1460 non-null   int64
 5   Street         1460 non-null   object
 6   Alley          91 non-null     object
 7   LotShape       1460 non-null   object
 8   LandContour    1460 non-null   object
 9   Utilities      1460 non-null   object
 10  LotConfig      1460 non-null   object
 11  LandSlope      1460 non-null   object
 12  Neighborhood   1460 non-null   object
 13  Condition1     1460 non-null   object
 14  Condition2     1460 non-null   object
 15  BldgType       1460 non-null   object
 16  HouseStyle     1460 non-null   object
 17  OverallQual    1460 non-null   int64
 18  OverallCond    1460 non-null   int64
 19  YearBuilt      1460 non-null   int64
 20  YearRemodAdd   1460 non-null   int64
 21  RoofStyle      1460 non-null   object
 22  RoofMatl       1460 non-null   object
 23  Exterior1st    1460 non-null   object
 24  Exterior2nd    1460 non-null   object
 25  MasVnrType     1452 non-null   object
 26  MasVnrArea     1452 non-null   float64
 27  ExterQual      1460 non-null   object
 28  ExterCond      1460 non-null   object
 29  Foundation     1460 non-null   object
 30  BsmtQual       1423 non-null   object
 31  BsmtCond       1423 non-null   object
 32  BsmtExposure   1422 non-null   object
 33  BsmtFinType1   1423 non-null   object
 34  BsmtFinSF1     1460 non-null   int64
 35  BsmtFinType2   1422 non-null   object
 36  BsmtFinSF2     1460 non-null   int64
 37  BsmtUnfSF      1460 non-null   int64
 38  TotalBsmtSF    1460 non-null   int64
 39  Heating        1460 non-null   object
 40  HeatingQC      1460 non-null   object
 41  CentralAir     1460 non-null   object
 42  Electrical     1459 non-null   object
 43  1stFlrSF       1460 non-null   int64
 44  2ndFlrSF       1460 non-null   int64
 45  LowQualFinSF   1460 non-null   int64
 46  GrLivArea      1460 non-null   int64
 47  BsmtFullBath   1460 non-null   int64
 48  BsmtHalfBath   1460 non-null   int64
 49  FullBath       1460 non-null   int64
 50  HalfBath       1460 non-null   int64
 51  BedroomAbvGr   1460 non-null   int64
 52  KitchenAbvGr   1460 non-null   int64
 53  KitchenQual    1460 non-null   object
 54  TotRmsAbvGrd   1460 non-null   int64
 55  Functional     1460 non-null   object
 56  Fireplaces     1460 non-null   int64
 57  FireplaceQu    770 non-null    object
 58  GarageType     1379 non-null   object
 59  GarageYrBlt    1379 non-null   float64
 60  GarageFinish   1379 non-null   object
 61  GarageCars     1460 non-null   int64
 62  GarageArea     1460 non-null   int64
 63  GarageQual     1379 non-null   object
 64  GarageCond     1379 non-null   object
 65  PavedDrive     1460 non-null   object
 66  WoodDeckSF     1460 non-null   int64
 67  OpenPorchSF    1460 non-null   int64
 68  EnclosedPorch  1460 non-null   int64
 69  3SsnPorch      1460 non-null   int64
 70  ScreenPorch    1460 non-null   int64
 71  PoolArea       1460 non-null   int64
 72  PoolQC         7 non-null      object
 73  Fence          281 non-null    object
 74  MiscFeature    54 non-null     object
 75  MiscVal        1460 non-null   int64
 76  MoSold         1460 non-null   int64
 77  YrSold         1460 non-null   int64
 78  SaleType       1460 non-null   object
 79  SaleCondition  1460 non-null   object
 80  SalePrice      1460 non-null   int64
dtypes: float64(3), int64(35), object(43)
memory usage: 924.0+ KB

* Train has 81 columns, including Sale Price, and LOTS of null values
* Id from 1 to 1459 is Train data, which means it has a Sale Price

#### Test data

In [101]:
# Test data
#Test.head()

In [102]:
#Test.info()

* Train has 81 columns, including Sale Price, and LOTS of null values
* Id from 1461 to 2919 is Test data, which means I must PREDICT a Sale Price

* Both datasets have lots of null values, so I'll combine them and treat them together to prepare the data for prediction.
* I must be careful because in some fields the missing value actually means something, so this might be tricky

In [103]:
#fullData = pd.concat([Train, Test], axis=0).reset_index(drop=True)
#fullData.shape

In [104]:
fullData.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 81 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1460 non-null   int64
 1   MSSubClass     1460 non-null   int64
 2   MSZoning       1460 non-null   object
 3   LotFrontage    1201 non-null   float64
 4   LotArea        1460 non-null   int64
 5   Street         1460 non-null   object
 6   Alley          91 non-null     object
 7   LotShape       1460 non-null   object
 8   LandContour    1460 non-null   object
 9   Utilities      1460 non-null   object
 10  LotConfig      1460 non-null   object
 11  LandSlope      1460 non-null   object
 12  Neighborhood   1460 non-null   object
 13  Condition1     1460 non-null   object
 14  Condition2     1460 non-null   object
 15  BldgType       1460 non-null   object
 16  HouseStyle     1460 non-null   object
 17  OverallQual    1460 non-null   int64
 18  OverallCond    1460 non-null   int64
 19  YearBuilt      1460 non-null   int64
 20  YearRemodAdd   1460 non-null   int64
 21  RoofStyle      1460 non-null   object
 22  RoofMatl       1460 non-null   object
 23  Exterior1st    1460 non-null   object
 24  Exterior2nd    1460 non-null   object
 25  MasVnrType     1452 non-null   object
 26  MasVnrArea     1452 non-null   float64
 27  ExterQual      1460 non-null   object
 28  ExterCond      1460 non-null   object
 29  Foundation     1460 non-null   object
 30  BsmtQual       1423 non-null   object
 31  BsmtCond       1423 non-null   object
 32  BsmtExposure   1422 non-null   object
 33  BsmtFinType1   1423 non-null   object
 34  BsmtFinSF1     1460 non-null   int64
 35  BsmtFinType2   1422 non-null   object
 36  BsmtFinSF2     1460 non-null   int64
 37  BsmtUnfSF      1460 non-null   int64
 38  TotalBsmtSF    1460 non-null   int64
 39  Heating        1460 non-null   object
 40  HeatingQC      1460 non-null   object
 41  CentralAir     1460 non-null   object
 42  Electrical     1459 non-null   object
 43  1stFlrSF       1460 non-null   int64
 44  2ndFlrSF       1460 non-null   int64
 45  LowQualFinSF   1460 non-null   int64
 46  GrLivArea      1460 non-null   int64
 47  BsmtFullBath   1460 non-null   int64
 48  BsmtHalfBath   1460 non-null   int64
 49  FullBath       1460 non-null   int64
 50  HalfBath       1460 non-null   int64
 51  BedroomAbvGr   1460 non-null   int64
 52  KitchenAbvGr   1460 non-null   int64
 53  KitchenQual    1460 non-null   object
 54  TotRmsAbvGrd   1460 non-null   int64
 55  Functional     1460 non-null   object
 56  Fireplaces     1460 non-null   int64
 57  FireplaceQu    770 non-null    object
 58  GarageType     1379 non-null   object
 59  GarageYrBlt    1379 non-null   float64
 60  GarageFinish   1379 non-null   object
 61  GarageCars     1460 non-null   int64
 62  GarageArea     1460 non-null   int64
 63  GarageQual     1379 non-null   object
 64  GarageCond     1379 non-null   object
 65  PavedDrive     1460 non-null   object
 66  WoodDeckSF     1460 non-null   int64
 67  OpenPorchSF    1460 non-null   int64
 68  EnclosedPorch  1460 non-null   int64
 69  3SsnPorch      1460 non-null   int64
 70  ScreenPorch    1460 non-null   int64
 71  PoolArea       1460 non-null   int64
 72  PoolQC         7 non-null      object
 73  Fence          281 non-null    object
 74  MiscFeature    54 non-null     object
 75  MiscVal        1460 non-null   int64
 76  MoSold         1460 non-null   int64
 77  YrSold         1460 non-null   int64
 78  SaleType       1460 non-null   object
 79  SaleCondition  1460 non-null   object
 80  SalePrice      1460 non-null   int64
dtypes: float64(3), int64(35), object(43)
memory usage: 924.0+ KB

### <span style='background :yellow' > Cleaning

In [105]:
# fix the columns with non numerical values

# field MSSubClass doesn't have missing values but is not in the right format
# it's the type of dwelling, so that shouldn't be an integer

fullData['MSSubClass'] = fullData['MSSubClass'].astype(str)

# columns where the missing value actually means something, so I'll fill it with "None" 
# these fields are already an object so no need to change format

fullData['Alley'] = fullData['Alley'].fillna("None")
fullData['BsmtQual'] = fullData['BsmtQual'].fillna("None")
fullData['BsmtCond'] = fullData['BsmtCond'].fillna("None")
fullData['BsmtExposure'] = fullData['BsmtExposure'].fillna("None")
fullData['BsmtFinType1'] = fullData['BsmtFinType1'].fillna("None")
fullData['BsmtFinType2'] = fullData['BsmtFinType2'].fillna("None")
fullData['FireplaceQu'] = fullData['FireplaceQu'].fillna("None")
fullData['GarageType'] = fullData['GarageType'].fillna("None")
fullData['GarageFinish'] = fullData['GarageFinish'].fillna("None")
fullData['GarageQual'] = fullData['GarageQual'].fillna("None")
fullData['GarageType'] = fullData['GarageType'].fillna("None")
fullData['GarageCond'] = fullData['GarageCond'].fillna("None")
fullData['PoolQC'] = fullData['PoolQC'].fillna("None")
fullData['Fence'] = fullData['Fence'].fillna("None")
fullData['MiscFeature'] = fullData['MiscFeature'].fillna("None")

# columns that are not numerical and have missing values, so I'll fill it with the mode 
# these fields are already an object so no need to change format

fullData['MSZoning'] = fullData['MSZoning'].fillna(fullData['MSZoning'].mode()[0])
fullData['Utilities'] = fullData['Utilities'].fillna(fullData['Utilities'].mode()[0])
fullData['Exterior1st'] = fullData['Exterior1st'].fillna(fullData['Exterior1st'].mode()[0])
fullData['Exterior2nd'] = fullData['Exterior2nd'].fillna(fullData['Exterior2nd'].mode()[0])
fullData['Functional'] = fullData['Functional'].fillna(fullData['Functional'].mode()[0])
fullData['MasVnrType'] = fullData['MasVnrType'].fillna(fullData['MasVnrType'].mode()[0])
fullData['Electrical'] = fullData['Electrical'].fillna(fullData['Electrical'].mode()[0])
fullData['KitchenQual'] = fullData['KitchenQual'].fillna(fullData['KitchenQual'].mode()[0])
fullData['SaleType'] = fullData['SaleType'].fillna(fullData['SaleType'].mode()[0])

In [106]:
fullData.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 81 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1460 non-null   int64
 1   MSSubClass     1460 non-null   object
 2   MSZoning       1460 non-null   object
 3   LotFrontage    1201 non-null   float64
 4   LotArea        1460 non-null   int64
 5   Street         1460 non-null   object
 6   Alley          1460 non-null   object
 7   LotShape       1460 non-null   object
 8   LandContour    1460 non-null   object
 9   Utilities      1460 non-null   object
 10  LotConfig      1460 non-null   object
 11  LandSlope      1460 non-null   object
 12  Neighborhood   1460 non-null   object
 13  Condition1     1460 non-null   object
 14  Condition2     1460 non-null   object
 15  BldgType       1460 non-null   object
 16  HouseStyle     1460 non-null   object
 17  OverallQual    1460 non-null   int64
 18  OverallCond    1460 non-null   int64
 19  YearBuilt      1460 non-null   int64
 20  YearRemodAdd   1460 non-null   int64
 21  RoofStyle      1460 non-null   object
 22  RoofMatl       1460 non-null   object
 23  Exterior1st    1460 non-null   object
 24  Exterior2nd    1460 non-null   object
 25  MasVnrType     1460 non-null   object
 26  MasVnrArea     1452 non-null   float64
 27  ExterQual      1460 non-null   object
 28  ExterCond      1460 non-null   object
 29  Foundation     1460 non-null   object
 30  BsmtQual       1460 non-null   object
 31  BsmtCond       1460 non-null   object
 32  BsmtExposure   1460 non-null   object
 33  BsmtFinType1   1460 non-null   object
 34  BsmtFinSF1     1460 non-null   int64
 35  BsmtFinType2   1460 non-null   object
 36  BsmtFinSF2     1460 non-null   int64
 37  BsmtUnfSF      1460 non-null   int64
 38  TotalBsmtSF    1460 non-null   int64
 39  Heating        1460 non-null   object
 40  HeatingQC      1460 non-null   object
 41  CentralAir     1460 non-null   object
 42  Electrical     1460 non-null   object
 43  1stFlrSF       1460 non-null   int64
 44  2ndFlrSF       1460 non-null   int64
 45  LowQualFinSF   1460 non-null   int64
 46  GrLivArea      1460 non-null   int64
 47  BsmtFullBath   1460 non-null   int64
 48  BsmtHalfBath   1460 non-null   int64
 49  FullBath       1460 non-null   int64
 50  HalfBath       1460 non-null   int64
 51  BedroomAbvGr   1460 non-null   int64
 52  KitchenAbvGr   1460 non-null   int64
 53  KitchenQual    1460 non-null   object
 54  TotRmsAbvGrd   1460 non-null   int64
 55  Functional     1460 non-null   object
 56  Fireplaces     1460 non-null   int64
 57  FireplaceQu    1460 non-null   object
 58  GarageType     1460 non-null   object
 59  GarageYrBlt    1379 non-null   float64
 60  GarageFinish   1460 non-null   object
 61  GarageCars     1460 non-null   int64
 62  GarageArea     1460 non-null   int64
 63  GarageQual     1460 non-null   object
 64  GarageCond     1460 non-null   object
 65  PavedDrive     1460 non-null   object
 66  WoodDeckSF     1460 non-null   int64
 67  OpenPorchSF    1460 non-null   int64
 68  EnclosedPorch  1460 non-null   int64
 69  3SsnPorch      1460 non-null   int64
 70  ScreenPorch    1460 non-null   int64
 71  PoolArea       1460 non-null   int64
 72  PoolQC         1460 non-null   object
 73  Fence          1460 non-null   object
 74  MiscFeature    1460 non-null   object
 75  MiscVal        1460 non-null   int64
 76  MoSold         1460 non-null   int64
 77  YrSold         1460 non-null   int64
 78  SaleType       1460 non-null   object
 79  SaleCondition  1460 non-null   object
 80  SalePrice      1460 non-null   int64
dtypes: float64(3), int64(34), object(44)
memory usage: 924.0+ KB

Now I'm missing the following:
* LotFrontage
* MasVnrArea
* BsmtFinSF1
* BsmtFinSF2
* TotalBsmtSF
* BsmtFullBath
* BsmtHalfBath
* Functional
* GarageYrBlt
* GarageCars
* GarageArea

In [107]:
# fill with median

fullData['LotFrontage'] = fullData['LotFrontage'].fillna(fullData['LotFrontage'].median())
fullData['MasVnrArea'] = fullData['MasVnrArea'].fillna(fullData['MasVnrArea'].median())
fullData['BsmtFinSF1'] = fullData['BsmtFinSF1'].fillna(fullData['BsmtFinSF1'].median())
fullData['BsmtFinSF2'] = fullData['BsmtFinSF2'].fillna(fullData['BsmtFinSF2'].median())
fullData['BsmtFullBath'] = fullData['BsmtFullBath'].fillna(fullData['BsmtFullBath'].median())
fullData['BsmtHalfBath'] = fullData['BsmtHalfBath'].fillna(fullData['BsmtHalfBath'].median())
fullData['GarageYrBlt'] = fullData['GarageYrBlt'].fillna(fullData['GarageYrBlt'].median())
fullData['GarageCars'] = fullData['GarageCars'].fillna(fullData['GarageCars'].median())
fullData['GarageArea'] = fullData['GarageArea'].fillna(fullData['GarageArea'].median())

In [108]:
fullData.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 81 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1460 non-null   int64
 1   MSSubClass     1460 non-null   object
 2   MSZoning       1460 non-null   object
 3   LotFrontage    1460 non-null   float64
 4   LotArea        1460 non-null   int64
 5   Street         1460 non-null   object
 6   Alley          1460 non-null   object
 7   LotShape       1460 non-null   object
 8   LandContour    1460 non-null   object
 9   Utilities      1460 non-null   object
 10  LotConfig      1460 non-null   object
 11  LandSlope      1460 non-null   object
 12  Neighborhood   1460 non-null   object
 13  Condition1     1460 non-null   object
 14  Condition2     1460 non-null   object
 15  BldgType       1460 non-null   object
 16  HouseStyle     1460 non-null   object
 17  OverallQual    1460 non-null   int64
 18  OverallCond    1460 non-null   int64
 19  YearBuilt      1460 non-null   int64
 20  YearRemodAdd   1460 non-null   int64
 21  RoofStyle      1460 non-null   object
 22  RoofMatl       1460 non-null   object
 23  Exterior1st    1460 non-null   object
 24  Exterior2nd    1460 non-null   object
 25  MasVnrType     1460 non-null   object
 26  MasVnrArea     1460 non-null   float64
 27  ExterQual      1460 non-null   object
 28  ExterCond      1460 non-null   object
 29  Foundation     1460 non-null   object
 30  BsmtQual       1460 non-null   object
 31  BsmtCond       1460 non-null   object
 32  BsmtExposure   1460 non-null   object
 33  BsmtFinType1   1460 non-null   object
 34  BsmtFinSF1     1460 non-null   int64
 35  BsmtFinType2   1460 non-null   object
 36  BsmtFinSF2     1460 non-null   int64
 37  BsmtUnfSF      1460 non-null   int64
 38  TotalBsmtSF    1460 non-null   int64
 39  Heating        1460 non-null   object
 40  HeatingQC      1460 non-null   object
 41  CentralAir     1460 non-null   object
 42  Electrical     1460 non-null   object
 43  1stFlrSF       1460 non-null   int64
 44  2ndFlrSF       1460 non-null   int64
 45  LowQualFinSF   1460 non-null   int64
 46  GrLivArea      1460 non-null   int64
 47  BsmtFullBath   1460 non-null   int64
 48  BsmtHalfBath   1460 non-null   int64
 49  FullBath       1460 non-null   int64
 50  HalfBath       1460 non-null   int64
 51  BedroomAbvGr   1460 non-null   int64
 52  KitchenAbvGr   1460 non-null   int64
 53  KitchenQual    1460 non-null   object
 54  TotRmsAbvGrd   1460 non-null   int64
 55  Functional     1460 non-null   object
 56  Fireplaces     1460 non-null   int64
 57  FireplaceQu    1460 non-null   object
 58  GarageType     1460 non-null   object
 59  GarageYrBlt    1460 non-null   float64
 60  GarageFinish   1460 non-null   object
 61  GarageCars     1460 non-null   int64
 62  GarageArea     1460 non-null   int64
 63  GarageQual     1460 non-null   object
 64  GarageCond     1460 non-null   object
 65  PavedDrive     1460 non-null   object
 66  WoodDeckSF     1460 non-null   int64
 67  OpenPorchSF    1460 non-null   int64
 68  EnclosedPorch  1460 non-null   int64
 69  3SsnPorch      1460 non-null   int64
 70  ScreenPorch    1460 non-null   int64
 71  PoolArea       1460 non-null   int64
 72  PoolQC         1460 non-null   object
 73  Fence          1460 non-null   object
 74  MiscFeature    1460 non-null   object
 75  MiscVal        1460 non-null   int64
 76  MoSold         1460 non-null   int64
 77  YrSold         1460 non-null   int64
 78  SaleType       1460 non-null   object
 79  SaleCondition  1460 non-null   object
 80  SalePrice      1460 non-null   int64
dtypes: float64(3), int64(34), object(44)
memory usage: 924.0+ KB

* Now all columns have non-null values, except from the Sale Price.
* Next step is dealing with the categorical values and encoding

### <span style='background :yellow' > Handling Categorical Features

In [109]:
# Make a copy of the dataset in case the encoding goes wrong

fullData2 = fullData.copy()

In [110]:
#columns to be encoded using get_dummies
fullData2.select_dtypes(np.object).columns

Index(['MSSubClass', 'MSZoning', 'Street', 'Alley', 'LotShape', 'LandContour',
       'Utilities', 'LotConfig', 'LandSlope', 'Neighborhood', 'Condition1',
       'Condition2', 'BldgType', 'HouseStyle', 'RoofStyle', 'RoofMatl',
       'Exterior1st', 'Exterior2nd', 'MasVnrType', 'ExterQual', 'ExterCond',
       'Foundation', 'BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1',
       'BsmtFinType2', 'Heating', 'HeatingQC', 'CentralAir', 'Electrical',
       'KitchenQual', 'Functional', 'FireplaceQu', 'GarageType',
       'GarageFinish', 'GarageQual', 'GarageCond', 'PavedDrive', 'PoolQC',
       'Fence', 'MiscFeature', 'SaleType', 'SaleCondition'],
      dtype='object')

In [111]:
#will encode all variables that are not integer or float64

dummiesDF = pd.get_dummies(fullData2.select_dtypes(np.object))
dummiesDF.shape

(1460, 281)

In [112]:
# append the dummies back together

fullData2 = fullData2.merge(dummiesDF,left_index=True,right_index=True)

# drop the encoded columns
fullData2.drop(['MSSubClass', 'MSZoning', 'Street', 'Alley', 'LotShape', 'LandContour',
       'Utilities', 'LotConfig', 'LandSlope', 'Neighborhood', 'Condition1',
       'Condition2', 'BldgType', 'HouseStyle', 'RoofStyle', 'RoofMatl',
       'Exterior1st', 'Exterior2nd', 'MasVnrType', 'ExterQual', 'ExterCond',
       'Foundation', 'BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1',
       'BsmtFinType2', 'Heating', 'HeatingQC', 'CentralAir', 'Electrical',
       'KitchenQual', 'Functional', 'FireplaceQu', 'GarageType',
       'GarageFinish', 'GarageQual', 'GarageCond', 'PavedDrive', 'PoolQC',
       'Fence', 'MiscFeature', 'SaleType', 'SaleCondition'], axis = 'columns', inplace = True)

In [113]:
fullData2.head()

,Id,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,BsmtFinSF2,...,SaleType_ConLw,SaleType_New,SaleType_Oth,SaleType_WD,SaleCondition_Abnorml,SaleCondition_AdjLand,SaleCondition_Alloca,SaleCondition_Family,SaleCondition_Normal,SaleCondition_Partial
0,1,65.0,8450,7,5,2003,2003,196.0,706,0,...,0,0,0,1,0,0,0,0,1,0
1,2,80.0,9600,6,8,1976,1976,0.0,978,0,...,0,0,0,1,0,0,0,0,1,0
2,3,68.0,11250,7,5,2001,2002,162.0,486,0,...,0,0,0,1,0,0,0,0,1,0
3,4,60.0,9550,7,5,1915,1970,0.0,216,0,...,0,0,0,1,1,0,0,0,0,0
4,5,84.0,14260,8,5,2000,2000,350.0,655,0,...,0,0,0,1,0,0,0,0,1,0

### <span style='background :yellow' > Understand Sale Price (target variable)

In [114]:
fullData2.SalePrice.describe()

count      1460.000000
mean     180921.195890
std       79442.502883
min       34900.000000
25%      129975.000000
50%      163000.000000
75%      214000.000000
max      755000.000000
Name: SalePrice, dtype: float64

* Average sale price is almost 181k, with a considerable St. Deviation of almost 80k
* Price is positively skewed, and is not aligned to normal distribution ("bell-shaped" curve)

In [115]:
priceColumn = fullData2['SalePrice']

In [116]:
origId = fullData2['Id']

### <span style='background :yellow' > Scale

In [141]:
fullData3 = fullData2.copy()
fullData3 = fullData3.drop('Id', axis = 1)

In [142]:
fullData3.shape

(1460, 317)

In [151]:
#X_mult
X_mult = fullData3.drop('SalePrice', axis=1)

#target
y_mult = fullData3.SalePrice

In [152]:
#split
X_train, X_test, y_train, y_test = train_test_split(X_mult, y_mult, test_size=0.2, random_state=1234)
print("training data size:",X_train.shape)
print("testing data size:",X_test.shape)

training data size: (1168, 316)
testing data size: (292, 316)

In [153]:
X_train.head()

,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,BsmtFinSF2,BsmtUnfSF,...,SaleType_ConLw,SaleType_New,SaleType_Oth,SaleType_WD,SaleCondition_Abnorml,SaleCondition_AdjLand,SaleCondition_Alloca,SaleCondition_Family,SaleCondition_Normal,SaleCondition_Partial
503,100.0,15602,7,8,1959,1997,0.0,1247,0,254,...,0,0,0,1,0,0,0,0,1,0
87,40.0,3951,6,5,2009,2009,76.0,0,0,612,...,0,1,0,0,0,0,0,0,0,1
500,21.0,1890,6,5,1973,1973,285.0,356,0,316,...,0,0,0,1,0,0,0,0,1,0
1332,67.0,8877,4,6,1938,1958,0.0,690,0,126,...,0,0,0,1,0,0,0,0,1,0
658,78.0,17503,6,5,1948,1950,0.0,0,0,912,...,0,0,0,1,1,0,0,0,0,0

In [154]:
#scale
#scaler = StandardScaler()
#scaler.fit(X_train)
#X_train = scaler.transform(X_train)
#X_test = scaler.transform(X_test)

In [155]:
# instantiate and fit 
multiple_linreg = LinearRegression()
multiple_linreg.fit(X_train, y_train)

coeffs = multiple_linreg.coef_
intercept =  multiple_linreg.intercept_

In [156]:
predictions = multiple_linreg.predict(X_test)

In [157]:
#generate predictions on training set and evaluate
print("Training set RMSE for Multi Linear Reg:",np.sqrt(metrics.mean_squared_error(y_test, predictions)))

Training set RMSE for Multi Linear Reg: 102081.9036548298

In [85]:
#remove SalePrice so it's not scaled
fullData3 = fullData3.drop(['SalePrice'], axis=1)

In [86]:
#scale
fullDataScaled = fullData3.copy()
sc = StandardScaler()
sc.fit(fullDataScaled)
sc.transform(fullDataScaled)

array([[-1.73145754, -0.19181473, -0.21787869, ..., -0.12653513,
         0.46393674, -0.30269297],
       [-1.7302708 ,  0.51193993, -0.07204408, ..., -0.12653513,
         0.46393674, -0.30269297],
       [-1.72908405, -0.0510638 ,  0.13719688, ..., -0.12653513,
         0.46393674, -0.30269297],
       ...,
       [ 1.72908405,  4.26529811,  1.24680804, ..., -0.12653513,
        -2.15546626, -0.30269297],
       [ 1.7302708 , -0.33256567,  0.0346054 , ..., -0.12653513,
         0.46393674, -0.30269297],
       [ 1.73145754,  0.23043806, -0.06862014, ..., -0.12653513,
         0.46393674, -0.30269297]])

In [87]:
fullDataScaled.head()

,Id,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,BsmtFinSF2,...,SaleType_ConLw,SaleType_New,SaleType_Oth,SaleType_WD,SaleCondition_Abnorml,SaleCondition_AdjLand,SaleCondition_Alloca,SaleCondition_Family,SaleCondition_Normal,SaleCondition_Partial
0,1,65.0,8450,7,5,2003,2003,196.0,706.0,0.0,...,0,0,0,1,0,0,0,0,1,0
1,2,80.0,9600,6,8,1976,1976,0.0,978.0,0.0,...,0,0,0,1,0,0,0,0,1,0
2,3,68.0,11250,7,5,2001,2002,162.0,486.0,0.0,...,0,0,0,1,0,0,0,0,1,0
3,4,60.0,9550,7,5,1915,1970,0.0,216.0,0.0,...,0,0,0,1,1,0,0,0,0,0
4,5,84.0,14260,8,5,2000,2000,350.0,655.0,0.0,...,0,0,0,1,0,0,0,0,1,0

In [75]:
fullDataScaled['SalePrice'] = priceColumn

In [76]:
fullDataScaled.head()

,Id,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,BsmtFinSF2,...,SaleType_New,SaleType_Oth,SaleType_WD,SaleCondition_Abnorml,SaleCondition_AdjLand,SaleCondition_Alloca,SaleCondition_Family,SaleCondition_Normal,SaleCondition_Partial,SalePrice
0,1,65.0,8450,7,5,2003,2003,196.0,706.0,0.0,...,0,0,1,0,0,0,0,1,0,208500.0
1,2,80.0,9600,6,8,1976,1976,0.0,978.0,0.0,...,0,0,1,0,0,0,0,1,0,181500.0
2,3,68.0,11250,7,5,2001,2002,162.0,486.0,0.0,...,0,0,1,0,0,0,0,1,0,223500.0
3,4,60.0,9550,7,5,1915,1970,0.0,216.0,0.0,...,0,0,1,1,0,0,0,0,0,140000.0
4,5,84.0,14260,8,5,2000,2000,350.0,655.0,0.0,...,0,0,1,0,0,0,0,1,0,250000.0

### <span style='background :yellow' > Split the data

Now I'll split the data into Train and Test again

In [32]:
newTrain = fullData3.loc[:Train.Id.max(), :].copy()
newTest = fullData3.loc[Train.Id.max() + 1:, :].copy()

In [92]:
newTrain.shape

(1461, 319)

In [90]:
#X_mult
X_mult = fullData3

#target
y_mult = fullData3.SalePrice

In [91]:
#split
X_train, X_test, y_train, y_test = train_test_split(X_mult, y_mult, test_size=0.4, random_state=1234)
print("training data size:",X_train.shape)
print("testing data size:",X_test.shape)

training data size: (876, 319)
testing data size: (585, 319)

In [ ]:
mult_feature_cols = ['acceleration', 'displacement', 'horsepower']
X_mult = newTrain
y_mult = newTrain.SalePrice

# instantiate and fit 
multiple_linreg = LinearRegression()
multiple_linreg.fit(X_mult, y_mult)

coeffs = multiple_linreg.coef_
intercept =  multiple_linreg.intercept_

In [ ]:
'''
X_wine_unscaled = wine_data[wine_features].astype(float)
scaler = StandardScaler()

knn_unsc = KNeighborsClassifier(n_neighbors=3)
knn_sc = KNeighborsClassifier(n_neighbors=3)

X_wine_scaled = scaler.fit_transform(wine_data[wine_features].astype(float))

y = wine_data[wine_target]
X_train,X_test,y_train,y_test = train_test_split(X_wine_scaled,y,
                                                 test_size=0.2,
                                                 random_state=1234)
X_train_unsc,X_test_unsc,y_train_unsc,y_test_unsc = train_test_split(X_wine_unscaled,
                                                                     y,
                                                                     test_size=0.2,
                                                                    random_state=1234)

knn_unsc.fit(X_train_unsc,y_train_unsc)
knn_sc.fit(X_train,y_train)
print("unscaled test accuracy:",metrics.accuracy_score(y_test_unsc,
                                                       knn_unsc.predict(X_test_unsc)))
print("scaled test accuracy:",metrics.accuracy_score(y_test,
                                                       knn_sc.predict(X_test)))
'''

### <span style='background :yellow' > 6. Multi Linear Regression